name: Build and publish release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_name:
        description: 'The name/title of the new release (e.g., "v1.0.0 Release")'
        required: true
        type: string
      tag_name:
        description: 'The tag name for the release (e.g., "v1.0.0")'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        go-version: [1.25]
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: windows-latest
            goos: windows
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: arm64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build and package (Linux/MacOS)
        id: build_and_package_linux
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          set -euo pipefail
          outdir="dist/${{ matrix.goos }}-${{ matrix.arch }}"
          mkdir -p "$outdir"
          binname=go-copy
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 \
          go build -ldflags "-s -w" -o "$outdir/$binname" ./cmd/go-copy/...
          tar -czf "${{ matrix.goos }}-${{ matrix.arch }}.tar.gz" -C dist "${{ matrix.goos }}-${{ matrix.arch }}"

      # - name: Build and package (MacOS)
      #   id: build_and_package_macos
      #   if: matrix.os == 'macos-latest' && matrix.arch == 'amd64'
      #   shell: bash
      #   run: |
      #     set -euo pipefail
      #     outdir="dist/${{ matrix.goos }}-${{ matrix.arch }}"
      #     mkdir -p "$outdir"
      #     binname=go-copy
      #     env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 \
      #     go build -ldflags "-s -w" -o "$outdir/$binname" ./cmd/go-copy/...
      #     tar -czf "${{ matrix.goos }}-${{ matrix.arch }}.tar.gz" -C dist "${{ matrix.goos }}-${{ matrix.arch }}"

      # - name: Build and package (MacOS Unsigned)
      #   id: build_and_package_macos_unsigned
      #   if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
      #   shell: bash
      #   run: |
      #     set -euo pipefail
      #     outdir="dist/${{ matrix.goos }}-${{ matrix.arch }}"
      #     mkdir -p "$outdir"
      #     binname=go-copy
      #     env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 \
      #     go build -ldflags "-s -w" -o "$outdir/$binname" ./cmd/go-copy/...
      #     tar -czf "${{ matrix.goos }}-${{ matrix.arch }}.tar.gz" -C dist "${{ matrix.goos }}-${{ matrix.arch }}"

      - name: Build and package (Windows)
        id: build_and_package_windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $outdir = "dist/${{ matrix.goos }}-${{ matrix.arch }}"
          New-Item -ItemType Directory -Path $outdir -Force | Out-Null
          $binname = 'go-copy.exe'
          $env:GOOS = 'windows'; $env:GOARCH = '${{ matrix.arch }}'; $env:CGO_ENABLED = '0'
          go build -ldflags "-s -w" -o "$outdir\$binname" ./cmd/go-copy/...
          Compress-Archive -Path "$outdir\*" -DestinationPath "${{ matrix.goos }}-${{ matrix.arch }}.zip"

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.arch }}
          path: |
            ${{ matrix.goos }}-${{ matrix.arch }}.tar.gz
            ${{ matrix.goos }}-${{ matrix.arch }}.zip

  publish:
    name: Create release and attach builds
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ inputs.tag_name }}
          release_name: ${{ inputs.release_name }}
          draft: false
          prerelease: false

      - name: Upload linux release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/linux-amd64/linux-amd64.tar.gz
          asset_name: go-copy-${{ inputs.tag_name }}-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload macos release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/macos-amd64/macos-amd64.tar.gz
          asset_name: go-copy-${{ inputs.tag_name }}-macos-amd64.zip
          asset_content_type: application/zip

      - name: Upload macos unsigned release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/macos-arm64/macos-arm64.tar.gz
          asset_name: go-copy-${{ inputs.tag_name }}-macos-arm64.zip
          asset_content_type: application/zip

      - name: Upload windows release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows-amd64/windows-amd64.zip
          asset_name: go-copy-${{ inputs.tag_name }}-windows-amd64.zip
          asset_content_type: application/zip
